---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v1.2.3"
    hooks:
      - id: check-merge-conflict
      - id: debug-statements
        stages: [commit]
      - id: detect-private-key
        stages: [commit]
      - id: detect-aws-credentials
        stages: [push]
      - id: check-ast
        stages: [push]
      - id: trailing-whitespace
        stages: [commit]
  - repo: https://github.com/psf/black
    rev: "20.8b1"
    hooks:
      - id: black
        language_version: python3
        exclude: generated/
        stages: [commit]
  - repo: https://gitlab.com/pycqa/flake8
    rev: "3.9.1"
    hooks:
      - id: flake8
        args:
          - "--config=setup.cfg"
        stages: [commit]
  - repo: https://github.com/PyCQA/pylint
    rev: "pylint-2.7.4"
    hooks:
      - id: pylint
        args:
          - "--rcfile=pylintrc"
        stages: [commit]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.812"
    hooks:
      - id: mypy
        name: mypy
        additional_dependencies:
          - pydantic==1.4
        stages: [commit]
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        pass_filenames: false
        language: system
        stages: [push]
        types: [file, python]
