---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v1.2.3"
    hooks:
      - id: check-merge-conflict
      - id: debug-statements
        stages: [push]
  - repo: https://github.com/psf/black
    rev: "19.10b0"
    hooks:
      - id: black
        language_version: python3
        stages: [commit]
  - repo: https://gitlab.com/pycqa/flake8
    rev: "3.7.9"
    hooks:
      - id: flake8
        args:
          - "--config=setup.cfg"
        stages: [commit]
  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: "v2.4.4"
    hooks:
      - id: pylint
        args:
          - "--rcfile=pylintrc"
        stages: [commit]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.770"
    hooks:
      - id: mypy
        name: mypy
        types: [file, python]
        additional_dependencies:
          - pydantic==1.4
        stages: [commit]
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        pass_filenames: false
        language: system
        stages: [commit]
        types: [file, python]
