name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
        if [ -f requirements-test.txt ]; then pip install -r requirements-test.txt; fi
    - name: Check formatting with black
      run: |
        # stop the build if there are formatting errors
        black .
    - name: Check formatting with flake8
      run: |
        # stop the build if there are formatting errors
        flake8 . --config=setup.cfg
    - name: Lint with pylint
      run: |
        # stop the build if there are Python lint errors
        pylint *.py --rcfile=pylintrc
    - name: Check types with mypy
      run: |
        # stop the build if there are type errors
        mypy *.py
    - name: Test with pytest
      run: |
        pytest
